In [ ]:
import numpy as np

In [ ]:
#Q1  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

arr1= np.random.randint(1,100, size=(3,3))

In [ ]:
arr1

array([[82, 25, 93],
       [23, 76, 47],
       [ 2, 50, 45]])

In [ ]:
arr1.T

array([[82, 23,  2],
       [25, 76, 50],
       [93, 47, 45]])

In [ ]:
#Q2 Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

arr2= np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr2.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr2.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#Q3 Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

arr_4x4=np.random.rand(4,4)

In [ ]:
arr_4x4

array([[0.54726268, 0.57097239, 0.84798893, 0.1025894 ],
       [0.13405326, 0.28932906, 0.73552298, 0.92291481],
       [0.88363014, 0.03766422, 0.0203113 , 0.43074028],
       [0.28071326, 0.76568439, 0.05822657, 0.20391718]])

In [ ]:
arr_6x6 = np.pad(arr_4x4, pad_width=1, mode='constant', constant_values=0)


In [ ]:
arr_6x6

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.54726268, 0.57097239, 0.84798893, 0.1025894 ,
        0.        ],
       [0.        , 0.13405326, 0.28932906, 0.73552298, 0.92291481,
        0.        ],
       [0.        , 0.88363014, 0.03766422, 0.0203113 , 0.43074028,
        0.        ],
       [0.        , 0.28071326, 0.76568439, 0.05822657, 0.20391718,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [ ]:
#Q4 Using NumPy, create an array of integers from 10 to 60 with a step of 5

arr3= np.arange(10,60,5)

In [ ]:
arr3

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [ ]:
#Q5 Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations(uppercase, lowercase, title case, etc.) to each element.

arr4= np.array(["python","numpy","pandas"])

In [ ]:
arr4

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
np.char.upper(arr4)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [ ]:
np.char.lower(arr4)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
np.char.title(arr4)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [ ]:
#Q6 Generate a NumPy array of words. Insert a space between each character of every word in the array

arr_normal= np.array(["python","numpy","pandas"])

In [ ]:
arr_normal

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [ ]:
arr_space= np.char.join(" ", arr_normal)

In [ ]:
arr_space

array(['p y t h o n', 'n u m p y', 'p a n d a s'], dtype='<U11')

In [ ]:
#Q7  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

arr_1= np.array([[2,4,6,8]])
arr_2= np.array([[1,3,5,7]])

In [ ]:
np.add(arr_1,arr_2)

array([[ 3,  7, 11, 15]])

In [ ]:
np.subtract(arr_1,arr_2)

array([[1, 1, 1, 1]])

In [ ]:
np.multiply(arr_1,arr_2)

array([[ 2, 12, 30, 56]])

In [ ]:
np.divide(arr_1,arr_2)

array([[2.        , 1.33333333, 1.2       , 1.14285714]])

In [ ]:
#Q8  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

mat_1= np.eye(5,5)

In [ ]:
mat_1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
diag_ele= np.diag(mat_1)

In [ ]:
diag_ele

array([1., 1., 1., 1., 1.])

In [ ]:
#Q9  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True


arr6= np.random.randint(1,1000, size=100)

prime_num= np.array([num for num in arr6 if is_prime(num)])

In [ ]:
arr6

array([777, 566, 536, 252, 523, 256, 525, 137, 954, 735, 832, 643, 885,
       557, 702, 754, 442, 274, 810, 604, 298, 397, 177, 991, 797, 960,
       568, 847, 785, 529, 728, 332, 607, 485, 439, 858, 316, 743, 893,
       194, 200, 206, 602, 279, 181, 741, 567, 506, 896, 523, 596, 821,
       454, 366, 545, 895, 120, 515, 649, 179, 194, 255, 994, 628, 414,
       287,  60, 901,   7, 307, 524, 855, 552, 465, 973, 407, 621,  27,
       206, 960, 881, 613, 965, 176, 857, 272, 302, 137, 936, 820,  48,
       368, 823, 240, 425, 352, 571, 500, 178, 402])

In [ ]:
prime_num

array([523, 137, 643, 557, 397, 991, 797, 607, 439, 743, 181, 523, 821,
       179,   7, 307, 881, 613, 857, 137, 823, 571])

In [ ]:
#Q10  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

daily_temp= np.random.randint(15,36, size=30)
daily_temp

array([33, 35, 19, 26, 20, 32, 26, 24, 23, 22, 23, 32, 27, 27, 34, 31, 16,
       27, 20, 30, 19, 16, 18, 21, 15, 20, 17, 32, 31, 33])

In [ ]:
weekly_temp= daily_temp[:28].reshape(4,7)
weekly_temp

array([[33, 35, 19, 26, 20, 32, 26],
       [24, 23, 22, 23, 32, 27, 27],
       [34, 31, 16, 27, 20, 30, 19],
       [16, 18, 21, 15, 20, 17, 32]])

In [ ]:
weekly_avg= np.mean(weekly_temp, axis=1)
weekly_avg

array([27.28571429, 25.42857143, 25.28571429, 19.85714286])

In [1]:
#Q 11  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

#NumPy is a library in Python that helps make math and data tasks easier and faster. Here's a simple breakdown:

#Purpose of NumPy:
   #Work with numbers: It allows us to handle large amounts of numbers easily.
   #Do math quickly: It helps do math tasks like adding or multiplying numbers quickly, even when there are a lot of them.
   #Analyze data: It’s useful for analyzing and working with big sets of data, which is important for jobs like data analysis or science.
#Advantages of NumPy:
    #Faster: It makes Python faster when doing math with lots of data.
    #Saves memory: It uses less space to store numbers than regular Python lists.
    #Easy math: It has many ready-to-use math functions that save time.
    #No loops: You can do things with whole groups of numbers at once, without writing long code.
#How NumPy helps Python:
   #Python is slow with large numbers on its own, but NumPy makes it fast.
   # It lets Python work with tables of numbers (like a spreadsheet) more easily, which is important in science and data.
#
#

In [2]:
#Q12  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

#Both np.mean() and np.average() in NumPy are used to find the average of numbers, but they have a small difference. Here's a simple comparison:

#np.mean():
   #Basic average: It calculates the simple average of numbers.
   #No weights: It treats all numbers equally, so it just adds them all up and divides by the total number.
   #Usage: Use it when you want a straightforward average with no extra conditions.
#np.average():
   #Weighted average: It can calculate a weighted average, which means some numbers can count more than others.
   #Can use weights: You can give certain numbers more importance by adding weights.
   #Usage: Use it when some numbers are more important, and you want to consider that in the average.
#When to use each:
  #Use np.mean() when all the numbers should be treated equally.
  #Use np.average() when you need to consider weights and make some numbers count more.
#

In [3]:
#Q13  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays

#Reversing a NumPy array can be done in different ways depending on the number of dimensions (1D, 2D, etc.). Here’s a simple explanation for both 1D and 2D arrays:

 #1D Array (One-dimensional):
   #For a 1D array (like a list of numbers), you can reverse it by using slicing.
#Example:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]  # This reverses the array

print(reversed_arr)  # Output: [5 4 3 2 1]


[5 4 3 2 1]


In [5]:
#2D Array (Two-dimensional):
 #For a 2D array (like a table of numbers), you can reverse it along rows or columns.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse rows
reversed_rows = arr_2d[::-1, :]  # Reverse the rows
print(reversed_rows)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [6]:
#Q14  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

#To determine the data type of elements in a NumPy array, you can use the dtype attribute. Here’s how you can do it:

import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)


#arr.dtype tells you the type of elements in the array, like integers (int64) or floats (float64).
#Importance of Data Types:
  #Data types are important in NumPy because:
#Memory Management: Different data types take up different amounts of memory. For example, an int32 (integer) takes less memory than a float64 (decimal number).
  #Using the correct data type saves memory, especially when working with large datasets.
  #Performance: Operations in NumPy are faster when using the correct data type. If you use a simpler data type (like int32 instead of float64), NumPy can process calculations more quickly.
  #Choosing the right type improves performance, especially in calculations with big arrays.

int64


In [7]:
#Q15  Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

#In NumPy, an ndarray (short for "N-dimensional array") is a type of array that can store numbers in multiple dimensions (1D, 2D, etc.). It is the main data structure used in NumPy.

#Key Features of ndarray:
   #Fixed size: Once created, the size of an ndarray cannot be changed.
   #Homogeneous: All elements in an ndarray must be of the same data type (e.g., all integers or all floats).
   #Efficient memory usage: It uses less memory than Python lists because it stores data more efficiently.
   #Supports multiple dimensions: Unlike Python lists, which are mostly 1D, ndarrays can be 1D, 2D, or higher (like a matrix or 3D array).
   #Vectorized operations: You can perform operations on entire arrays at once without loops. This makes it faster and easier to work with large amounts of data.
#Example:

arr = np.array([1, 2, 3])  # 1D ndarray
arr_2d = np.array([[1, 2], [3, 4]])  # 2D ndarray

#How ndarray Differs from Python Lists:
   #Speed: ndarrays are much faster for numerical operations compared to Python lists.
   #Memory: ndarrays use less memory because they store data more efficiently.
   #Operations: You can do mathematical operations directly on ndarrays (e.g., add, subtract, multiply), while with lists, you need to use loops.
   #Data Type: ndarrays store elements with the same data type, but lists can have elements with different types (e.g., integers, strings).

In [8]:
#Q16 . Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

#NumPy arrays offer significant performance benefits over Python lists, especially when dealing with large-scale numerical operations. Here’s a simple explanation of why:

#1. Speed:
  #NumPy arrays are much faster than Python lists for numerical operations. This is because NumPy is implemented in C, which makes operations on arrays faster.
  #Python lists are slower because they are more flexible (they can hold different data types) but lack optimization for numerical tasks.
#Example:
  #If you add two large arrays or lists element by element, NumPy performs the task much faster.

#2. Memory Efficiency:
   #NumPy arrays use less memory. This is because they store elements of the same type (like all integers or all floats) in a continuous block of memory.
   #Python lists are less memory efficient because they store elements as separate objects, even if they are the same type.
#3. Vectorized Operations:
   #NumPy arrays support vectorized operations, meaning you can perform math on entire arrays without needing to write loops. This is both faster and easier to code.
#Example: Adding two arrays in NumPy is done in one step: arr1 + arr2.
   #Python lists require loops for such operations, which slows things down for large datasets.
#Example: With lists, you'd have to use a for loop to add elements one by one.

In [9]:
#Q17 Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

#In NumPy, vstack() and hstack() are used to stack arrays together, but they do so in different directions:

#1. vstack() (Vertical Stack):
  #Purpose: Stacks arrays vertically, one on top of the other, like rows.
  #Usage: Use vstack() when you want to combine arrays along the vertical axis (like adding more rows to a table).

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.vstack((arr1, arr2))
print(result)


[[1 2 3]
 [4 5 6]]


In [10]:
#2. hstack() (Horizontal Stack):
   #Purpose: Stacks arrays horizontally, side by side, like adding more columns.
   #Usage: Use hstack() when you want to combine arrays along the horizontal axis (like adding more columns to a table).

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.hstack((arr1, arr2))
print(result)

#Key Differences:
#vstack(): Adds arrays vertically (in rows).
#hstack(): Adds arrays horizontally (in columns).

[1 2 3 4 5 6]


In [11]:
#Q18   Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

#In NumPy, the fliplr() and flipud() methods are used to reverse the order of elements in arrays, but they do so in different directions. Here’s a simple explanation of both methods and their effects on different array dimensions:

#1. fliplr() (Flip Left to Right):
  #Purpose: This method flips the array in the left-to-right direction.
  #Effect on 2D Arrays: It reverses the order of columns for each row.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = np.fliplr(arr)
print(result)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [12]:
#2. flipud() (Flip Up to Down):
  #Purpose: This method flips the array in the up-to-down direction.
  #Effect on 2D Arrays: It reverses the order of rows.

result = np.flipud(arr)
print(result)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [15]:
#Effects on Different Array Dimensions:
#1D Array:
  #Both methods will behave the same because there's only one dimension to flip.
#Example (1D Array):

arr_1d = np.array([1, 2, 3, 4, 5])

# Reversing a 1D array using slicing
reversed_arr = arr_1d[::-1]

print(reversed_arr)




[5 4 3 2 1]


In [16]:
#Q19  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

#The array_split() method in NumPy is used to divide an array into multiple sub-arrays. It allows you to split an array into sections along a specified axis.
#Key Features of array_split():
  #Flexible splitting: You can specify how many parts you want to split the array into.
  #Handles uneven splits: If the array can't be split evenly, array_split() distributes the remaining elements among the sub-arrays as evenly as possible.

#1. Splitting an Array into Equal Parts:

arr = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 equal parts
result = np.array_split(arr, 3)
print(result)




[array([1, 2]), array([3, 4]), array([5, 6])]


In [17]:
#2. Handling Uneven Splits:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Split into 3 parts
result = np.array_split(arr, 3)
print(result)


[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [18]:
#Q20 . Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

#In NumPy, vectorization and broadcasting are two key concepts that help improve the efficiency of array operations. Here’s a simple explanation of both:
#1. Vectorization:
  #Definition: Vectorization refers to the process of applying operations to entire arrays or large datasets at once, instead of using loops.
  #How it works: Instead of iterating through each element in an array, NumPy performs operations on the whole array in a single step, which is optimized in the background (usually in C).

arr = np.array([1, 2, 3, 4, 5])

# Using vectorization to add 10 to each element
result = arr + 10
print(result)



[11 12 13 14 15]


In [19]:
#2. Broadcasting:
#Definition: Broadcasting is a technique that allows NumPy to perform operations on arrays of different shapes by "stretching" the smaller array across the larger array.
#How it works: When performing operations, NumPy compares the shapes of the arrays involved. If the dimensions are compatible, it can automatically adjust the smaller array to match the shape of the larger one.

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

arr2 = np.array([10, 20, 30])  # 1D array

# Broadcasting arr2 across arr1
result = arr1 + arr2
print(result)


[[11 22 33]
 [14 25 36]]


In [20]:
# Contribution to Efficient Array Operations:
#Speed: Both vectorization and broadcasting reduce the need for explicit loops, making operations much faster. They utilize optimized C and Fortran libraries in the background.
#Simplicity: They simplify code by allowing you to write more concise operations, which is easier to read and maintain.
#Memory Efficiency: Broadcasting avoids the need to create large temporary arrays, which saves memory.